### Naive Bayes ML Algorithm Implementation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_iris

In [7]:
x, y = load_iris(return_X_y=True)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [8]:
x_train

array([[5. , 3.6, 1.4, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.8, 5.1, 1.5],
       [6.4, 3.1, 5.5, 1.8],
       [6.6, 3. , 4.4, 1.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3

In [10]:
from sklearn.naive_bayes import BernoulliNB

model = BernoulliNB()
bnb = model.fit(x_train, y_train)
bnb_pred = bnb.predict(x_test)

In [17]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Bernoulli:")
print("Accuracy Score:", accuracy_score(y_test, bnb_pred))
print("Classification Report:", classification_report(y_test, bnb_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, bnb_pred))

Bernoulli:
Accuracy Score: 0.2894736842105263
Classification Report:               precision    recall  f1-score   support

           0       0.00      0.00      0.00        15
           1       0.29      1.00      0.45        11
           2       0.00      0.00      0.00        12

    accuracy                           0.29        38
   macro avg       0.10      0.33      0.15        38
weighted avg       0.08      0.29      0.13        38

Confusion Matrix:
 [[ 0 15  0]
 [ 0 11  0]
 [ 0 12  0]]


/Users/santhoshib/miniconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/santhoshib/miniconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/santhoshib/miniconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", 

In [18]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
gnb = model.fit(x_train, y_train)
gnb_pred = gnb.predict(x_test)

print("Gaussian:")
print("Accuracy Score:", accuracy_score(y_test, gnb_pred))
print("Classification Report:", classification_report(y_test, gnb_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, gnb_pred))

Gaussian:
Accuracy Score: 1.0
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

Confusion Matrix:
 [[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [16]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
mnb = model.fit(x_train, y_train)
mnb_pred = mnb.predict(x_test)

print("Multinomial:")
print("Accuracy Score:", accuracy_score(y_test, mnb_pred))
print("Classification Report:", classification_report(y_test, mnb_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, mnb_pred))

Multinomial:
Accuracy Score: 0.9736842105263158
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.92      1.00      0.96        11
           2       1.00      0.92      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

Confusion Matrix:
 [[15  0  0]
 [ 0 11  0]
 [ 0  1 11]]
